/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Tue Jul 29 18:36:27 2025 */

/* parameterized module instance */
pll_50_in __ (.CLK( ), .CLKOP( ), .LOCK( ));
